### ISSUE TITLE
Getting a deprecation warning about this step in the action in V3 / V4 

### ISSUE THREAD

**Issue by cAstraea** [symfonycorp/security-checker-action#8]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by jrfnl** [comment]
Looks like this is actually related to the underlying tooling: https://github.com/fabpot/local-php-security-checker/issues/67

**Comment by fabpot** [comment]
Fixed now

**Comment by jrfnl** [comment]
@fabpot Thanks Fabien!

**Comment by spaze** [comment]
NB: This has not been released yet, it was fixed in the local PHP checker 2.0.6, but the fix wasn't propagated up to this action:
- The CLI tool requires github.com/fabpot/local-php-security-checker/v2 v2.0.**5**
- This repo has a tag but not a v5 release that would use the CLI image

UPDATE: The CLI tool now uses 2.0.6 (https://github.com/symfony-cli/symfony-cli/commit/11b775a3394ff2aa76e5669625a4ff1f361069cc) and the action can specify a tag, not a release, although the release would still be nice (#10)
